### PR TITLE
Dynamic joy

### PR DESCRIPTION
**Pull request by haryngod**
- dynamic reconfigure client for joystick.
- add launch for unit testing.
- connection loop for client

### CODE REVIEW

**Comment by stonier** [comment]
- `BagJoystick` -> `ReconfigureJoystick`
- `reconfigure_joystick.launch` -> `demo_reconfigure_joystick.launch`
- `rospy.spin()` instead of a kinda doing nothing `custom spin`.

**Comment by stonier** [comment]
@haryngod why is `magic_button_relay.py` → `joystick_map_bagging_button.py`?

**Comment by haryngod** [comment]
@stonier Didn't you let me change that? 

Ah, I thought you want to edit all the name should be renamed. Then I didn't back to origin...

**Comment by stonier** [comment]
@haryngod Thinking hats required!

Across so many packages, **scope** is an important concept. Someone else looking at this repo has absolutely no idea about `joystick_map_bagging` and does not need to. This kind of thing will just make it confusing for users and future developers of this package.

**Pull request merged**
