### PR TITLE
doubly namespaced.

### PR DESCRIPTION
**Pull request by jihoonl**

### CODE REVIEW

**Comment by jihoonl** [comment]
http://answers.ros.org/question/126391/nodelet-usage-and-its-role-in-designing-a-complex-controller/

**Comment by bit-pirate** [comment]
> http://answers.ros.org/question/126391/nodelet-usage-and-its-role-in-designing-a-complex-controller/

What has this long Q&A to do with this PR? Please point to the related parts inside.

**Comment by jihoonl** [comment]
I cannot get a link of my comment. see my comment on ahendrix's answer.

**Comment by bit-pirate** [comment]
> I cannot get a link of my comment. see my comment on ahendrix's answer.

That's indeed a missing function. With some trickery it is possible https://together.jolla.com/question/9077/askbot-expose-comment-anchors-for-direct-linking/ , but that should be much easier: http://askbot.org/en/question/12335/get-links-to-comments/

Anyway, I have found your comment and now understand the issue. Merging.

**Comment by bit-pirate** [comment]
Please delete the branch, if not needed any more.

**Pull request merged**
